name: app_doan_nhandien
description: "Do an co so"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.0+5
  permission_handler: ^10.4.0
  tflite_flutter: ^0.9.0
  tflite: ^1.1.2
  image_picker: ^1.0.4
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/flower_model.tflite
